### ISSUE TITLE
Raising the mouse pointer would be great! Constant healthbar and name showing due to pointer being at x/2 and y/2! And spells can benefit from this too!

### ISSUE THREAD

**Issue by NovaZek** [iZastic/vrising-thirdpersoncamera#1]
Hey there!
I was running a similar modification on this game via AHK.
Since I am using a 2K display (2560x1440), I aimed for the middle (1280x720), but raised the Y-axis by 150 pixels.
Why? Because of the constantly displaying healthbar with name on the upper screen.

Would be appreciated, if you could just increase the pointer accordingly to the screen resolution (x/2, (y/2)-150px OR similar multiplier).

Oh, and another issue noticable quite heavily with the mouse pointer being so close to the center:
Shooting spells will be more likely shoot off into left or right directions, when moving into their mirrored perspective (walking left and casting a shooting-spell will shoot the orbs to the right (not straight) and vice versa).
This can also be fixed with a more up pointing background mouse pointer, also makes on floor castings (AOE spells) more aimable overall.

**Comment by iZastic** [comment]
Added configuration options for offsets and now set mouse position using those offsets.
